### ISSUE TITLE
Can't seem to compile this

### ISSUE THREAD

**Issue by autodidaddict** [alichay/zig-wasm3#1]
When running `zig build` on zig `0.7.1` I get the following output:

```
/submod_build_plugin.zig:39:25: error: container 'std.ascii' has no member called 'endsWithIgnoreCase'
            if(std.ascii.endsWithIgnoreCase(ent.name, ".c")) {
                        ^
./gyro_plugin.zig:26:25: error: container 'std.ascii' has no member called 'startsWithIgnoreCase'
            if(std.ascii.startsWithIgnoreCase(line, "github wasm3 wasm3")) {
```

**Comment by alichay** [comment]
It's very difficult (and sometimes impossible) to target multiple versions of zig at a time, as the language moves so fast, so unfortunately this project only supports master branch zig for now.

I've updated the readme with some very basic usage instructions, including the version requirement. Sorry for the inconvenience!
