### ISSUE TITLE
unable to build on 0.9.1

### ISSUE THREAD

**Issue by OfekShochat** [alichay/zig-wasm3#2]
hello!
for some reason, I get this: `error: expected type 'std.mem.Allocator', found '*const (bound fn(*std.heap.FixedBufferAllocator) std.mem.Allocator)'` on https://github.com/alichay/zig-wasm3/blob/main/submod_build_plugin.zig#L109. changing `&fba.allocator` to `fba.allocator()` works...
thanks aot

EDIT: also c_void doesn't exist?
EDIT2: https://ziglang.org/download/0.9.0/release-notes.html#c_void-renamed-to-anyopaque

**Comment by alichay** [comment]
Thanks for reporting this! I don't really use Zig anymore since moving over to using Rust, so I never know when this thing's broken

I'll try to patch this up real quick :)

**Comment by alichay** [comment]
Fixed in 0ee2228!

**Comment by OfekShochat** [comment]
Hello! Im actually doing the opposite :P
